### ISSUE TITLE
[Bug]: Since update my Black Desert Online launcher wont open

### ISSUE THREAD

**Issue by kritikalds** [LeagueOfPoro/CapsuleFarmerEvolved#123]
![kép_2023-02-10_175656207](https://user-images.githubusercontent.com/10689969/218150551-da11305b-f988-4417-ab46-2a82276f8d66.png)
### What happened?

I downloaded the newest (v1.3) update, and the moment i opened the .exe file, my game closed and after that it said check my internet connection.. There was nothing wrong with my internet connection before, and to be sure i did the same on my other pc and the same thing happened.
I switched back to v1.2 and the game now opens, but seems like something is still wrong, because i cant update the game via launcher...

### What should happen?

Open the game, and the upadater should work.

### Capsule Farmer Version

v1.3

### Operating System

Windows 10

### My issue is not a question

- [X] I acknowledge that this issue is not a question or feature request.

**Comment by auroraisluna** [comment]
This application isn't storing any data on your computer or altering any files other than the `session` folder found in the same application were you downloaded the exe of the app. 

Please send your farmer logs, as the issue format requires. And additionally would be helpful to send your blackdessert update.log file the popup mentions.  

Re-open when done.
