### ISSUE TITLE
[Bug]: CapsuleFarmer has the wrong installation command line on docker

### ISSUE THREAD

**Issue by snakexgc** [LeagueOfPoro/CapsuleFarmerEvolved#125]
### What happened?

In the wiki,CapsuleFarmer has the wrong installation command line on docker

docker run -it --restart unless-stopped --name CapsuleFarmer -d -v /path/to/config.yaml:/config/config.yaml  leagueofporo/capsulefarmer:master

### What should happen?

You need to modify this command to "docker run -it --restart unless-stopped --name CapsuleFarmer -d -v **/config/config.yaml**:/config/config.yaml  leagueofporo/capsulefarmer:master"

I made the font bold where it needed to be changed, and asked the developer to see if there were any errors

### Capsule Farmer Version

v1.3

### Operating System

Other (Non Windows are not natively supported)

### Operating System Version

ubuntu20 docker

### Relevant log output

```shell
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/path/to/config.yaml" to rootfs at "/config/config.yaml": mount /path/to/config.yaml:/config/config.yaml (via /proc/self/fd/7), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.
```

### Notes

I looked at the directory after going into the docker container and found that there was an error in the mapping

### My issue is not a question

- [X] I acknowledge that this issue is not a question or feature request.

**Comment by Penguax** [comment]
Wiki also states 

> Edit the /path/to/config.yaml to the absolute path to your [configuration] file.

**Comment by auroraisluna** [comment]
The label `/path/to/` and instruction as mentioned by Penguax, are exactly what the user should do. 
Replace with the full path to the config file, and if that means the config is inside the config folder (as by default) or to a different folder, it is up to the user to decide and modify accordingly.

The command is not wrong, the fault is at the user for not modifying the path as required. Change not needed.
