### ISSUE TITLE
[Bug]: No new games in the next 19:42 hours, LCK starts in 42min

### ISSUE THREAD

**Issue by RomeoAlphaEkko** [LeagueOfPoro/CapsuleFarmerEvolved#126]
### What happened?

![image](https://user-images.githubusercontent.com/89660477/218241676-15d983a1-3fec-4ffe-a9ec-613558ae8647.png)

### What should happen?

3 different leagues lck, lpl, ljl are starting within the next 3 hours 
![image](https://user-images.githubusercontent.com/89660477/218241722-d261bf4e-1b7c-405d-ac87-ec80cec6b7a6.png)

### Capsule Farmer Version

v1.3

### Operating System

Windows 10

### Operating System Version

windows 10 22h2 19045.2546

### Relevant log output

```shell
-
```

### My issue is not a question

- [X] I acknowledge that this issue is not a question or feature request.

**Comment by auroraisluna** [comment]
Fixed in #124
