### ISSUE TITLE
[Bug]: i cant run v1.3 but v1.2 works

### ISSUE THREAD

**Issue by x1207349263** [LeagueOfPoro/CapsuleFarmerEvolved#127]
### What happened?

![image](https://user-images.githubusercontent.com/110819542/218241665-39cac20d-83b0-4f09-b205-4350458063be.png)
as the pic showed.i dont know whats going on.I've tried using vpn but it didnt work.Last night i can run it normally

### What should happen?

As described above

### Capsule Farmer Version

v1.3

### Operating System

Windows 10

### My issue is not a question

- [X] I acknowledge that this issue is not a question or feature request.

**Comment by auroraisluna** [comment]
Please edit your post with the entire details of the issue request and include logs. Re-open your issue once completed.  

We recommend asking in our Discord first before making the issue as it could be user error.
