### ISSUE TITLE
[Wiki]: Questions or Discussions template - bad link

### ISSUE THREAD

**Issue by XaaRii** [LeagueOfPoro/CapsuleFarmerEvolved#135]
### What is your request?

[in this file](https://github.com/LeagueOfPoro/CapsuleFarmerEvolved/tree/master/.github/ISSUE_TEMPLATE/config.yml)

The button points to `https://discord.gg/ebm5MJNvHU/`, which redirects to the [discord's main page](https://discord.com/).
I suggest replacing it with this one instead: `https://discord.com/invite/ebm5MJNvHU`
i believe the problem was caused by discord changing the domain in the past and not properly handling redirects of invite links in a browser.

### My request is not related to the application it self

- [X] I acknowledge that this issue is not related to the application and is in fact a wiki request.

**Comment by Penguax** [comment]
Did some testing, it doesn't seem to be the link, it's actually the slash at the end.

Works: [https://discord.gg/ebm5MJNvHU](https://discord.gg/ebm5MJNvHU)
Doesnt: [https://discord.gg/ebm5MJNvHU/](https://discord.gg/ebm5MJNvHU/)

**Comment by XaaRii** [comment]
You're actually right, I didn't thought about that. Welp, learns something new every day, i guess.
Thanks for looking into it!
