### ISSUE TITLE
[Suggestion]: Minimize to System Tray

### ISSUE THREAD

**Issue by Dekamir** [LeagueOfPoro/CapsuleFarmerEvolved#138]
### What is your idea?

App may minimize to the System Tray to stay away from the user workspace and farm peacefully.
The app may also start minimized to tray.

This may work great with "Launch at startup/Start with OS", which is not currently implemented, but can currently be automated by other means.

### What should happen?

The config file may have two additional options:
- `minimizeToTray: bool`
- `startMinimized: bool`

If wanted, the app can allow users to set which button minimizes to tray or to the taskbar:
- `sendToTrayButton:` `close` or `minimize`

The executable may also have arguments like
- `--startToTray` or `--startMinimized`

This eventually requires the program to have a system tray icon. Single or double clicking it may restore the window, and right click will open the menu, allowing the user to close the program gracefully.

### My request is not a question

- [X] I acknowledge that this issue is not a question or a bug request.

**Comment by LeagueOfPoro** [comment]
This would work only on Windows and it is not a planned feature. You can use external tools, like https://www.softpedia.com/get/PORTABLE-SOFTWARE/System/System-Enhancements/Minimize-ToTray.shtml
