### ISSUE TITLE
[Bug]: the moment i open it it shows some text for a split second then crashes

### ISSUE THREAD

**Issue by Wordo1** [LeagueOfPoro/CapsuleFarmerEvolved#144]
### What happened?

![image](https://user-images.githubusercontent.com/125394240/218815854-b21674cb-1028-49b4-89e1-ad579a28dabc.png)

### What should happen?

to open the program properly

### Capsule Farmer Version

v1.3

### Operating System

Windows 10

### My issue is not a question

- [X] I acknowledge that this issue is not a question or feature request.

**Comment by Penguax** [comment]
Not bug, your config is setup incorrectly. please use config helper in the wiki.

**Comment by EvilRammus** [comment]
Had the same thing happen to me - I left out the colon after the account name
