### ISSUE TITLE
[Wiki]: Advanced linux - edits to systemd section, ExecStart 

### ISSUE THREAD

**Issue by Aluerie** [LeagueOfPoro/CapsuleFarmerEvolved#151]
### What is your request?

Not sure how to PR wiki edits 🤔 but I want to suggest small edits to [Advanced Linux - Systemd section](https://github.com/LeagueOfPoro/CapsuleFarmerEvolved/wiki/Advanced-Installation-for-Linux#systemd).
![image](https://user-images.githubusercontent.com/33165440/219225192-b609fdf4-80bf-4dad-9625-b07c0b7cf4c0.png)

- [ ] There (screenshot above^) should be 
  ```ini
  [Service]
  ExecStart=/usr/local/bin/pipenv run python3 path/to/CapsuleFarmerEvolved/src/main.py
  ```
  because we use `pipenv run` and 1.3 moved `main.py` into `/src`

- [ ] I think mention of `journalctl -u capsulefarmerevolved` (command that shows output-journal) would be handy, especially with `-e` flag that shows output from the very end where we can see the heartbeat/live/lastdrop table at its latest state.
![image](https://user-images.githubusercontent.com/33165440/219230062-16d2fbf5-e08d-4f26-a2d9-631a7ed04559.png)

- [ ] Also maybe use ``ini ``` codeblock to wrap `-.service` file content for fancy colours like I show in the 1st point for some readability value :x 

### My request is not related to the application it self

- [X] I acknowledge that this issue is not related to the application and is in fact a wiki request.

**Comment by auroraisluna** [comment]
Updated.

**Comment by qoshua** [comment]
Would also like to add-on to this,

Check if the service is running with
`$ systemctl status capsulefarmerevolved`

**Comment by zjinkai** [comment]
Feb 27 21:43:21 racknerd-226493 systemd[1]: Started CapsuleFarmerEvolved.
Feb 27 21:43:21 racknerd-226493 systemd[584]: capsulefarmerevolved.service: Changing to the requested working directory failed: No such file or directory
Feb 27 21:43:21 racknerd-226493 systemd[584]: capsulefarmerevolved.service: Failed at step CHDIR spawning /usr/local/bin/pipenv: No such file or directory
