### ISSUE TITLE
[Suggestion]: Add Location Geocode/Area to Config

### ISSUE THREAD

**Issue by WeirdPtr** [LeagueOfPoro/CapsuleFarmerEvolved#152]
### What is your idea?

Currently the Location Geocode/Area that is being sent to Riot is "CZ".
I think it would be beneficial to have the ability for customization in the `config.yaml`.

[Location-01](https://github.com/LeagueOfPoro/CapsuleFarmerEvolved/blob/93cd8b2bf0a895b9f3b516a71f33eb7a07275769/src/Browser.py#L188)

### What should happen?

Add a option to the `config.yaml` containing a geocode/area. 
If not provided or invalid use a predefined geocode/area.

### My request is not a question

- [x] I acknowledge that this issue is not a question or a bug request.

**Comment by auroraisluna** [comment]
I believe this is purely for tracking and analytics on Riot's end. Let them think Czechia is watching a billion of streams :P

**Comment by x-Wawa** [comment]
Hey, I would like to do it but [where's area is specified](https://github.com/LeagueOfPoro/CapsuleFarmerEvolved/blob/93cd8b2bf0a895b9f3b516a71f33eb7a07275769/src/Browser.py#L188) we can see two values :

```json
"geolocation": {
    "code": "CZ",
    "area": "EU"
}
```

If we can find different available language codes on [this page](https://developer.riotgames.com/docs/lol#data-dragon_languages), I have no idea of where does the area code come from, it does not match the [routing codes](https://developer.riotgames.com/docs/lol#routing-values)

So please where can we find all possible codes and area values?

**Comment by Penguax** [comment]
Lolesports page accesses 
https://lolesports.com/location.js

when manually checking the page it spits out this for me 
`window._geoinfo = {"code":"US","area":"NA","locale":"en-US"}` 

Would be a good way of adding this in instead of using a list that may not be accurate to riot games.
