### ISSUE TITLE
Docker image fails to build on arm based devices

### ISSUE THREAD

**Issue by Guido30** [LeagueOfPoro/CapsuleFarmerEvolved#16]
Hi

This tool can be run 24/7 on a raspberry pi to avoid having to keep the pc on to farm drops, when building the docker image on a Raspberry pi, the build fails since the image being pulled, python:3.10-slim, is only compatible with x86 machines

To fix this, i have changed to python:3.10-slim-buster, and everything works fine after that

Maybe adding a note on the docker instructions to let people know of this possibility and what to do in that case would be nice
Also i would suggest running the container with the following command instead:
`docker run -it --restart unless-stopped -d -v /path/to/config.yaml:/config/config.yaml capsulefarmerevolved`
so that the container will automatically restart on device reboot.

**Comment by LeagueOfPoro** [comment]
Done, thanks for the suggestion
