### ISSUE TITLE
[Suggestion]: PLEASE make the table less wide again!

### ISSUE THREAD

**Issue by CptPICHU** [LeagueOfPoro/CapsuleFarmerEvolved#176]
### What is your idea?

So the program has gotten so wide now. The extra space for "Lifetime drops" is making the program become just so much bigger for no reason especially on mobile or on SSH windows...

I really would suggest to pack Session and Lifetime drops in the same space divided by a "|" symbol.
This way, the program doesnt become INSANELY LARGE with a few accounts and like 8 Live Matches on.

### What should happen?

Combine the session and lifetime drops into the same space devided by "|"
This could be named "Session / Lifetime" and the Value diplayed like "4 | 180" for example.
Would safe much space and still look nicely.

### My request is not a question

- [X] I acknowledge that this issue is not a question or a bug request.

**Comment by LeagueOfPoro** [comment]
In config: `showHistoricalDrops: false`
