### ISSUE TITLE
Send 2FA codes one by one

### ISSUE THREAD

**Issue by Zvampish** [LeagueOfPoro/CapsuleFarmerEvolved#18]
Hi

I tried using multiple accounts using 2FA with the same email with the 2FA version and I noticed all 2FA codes arrived at exactly the same time to my inbox. This made it so I couldn't know which 2FA code was for which account. 

Is it possible to send the first code for the first account then wait until you type the second one and the send the next and so forth?

Or could you add a delay between accounts so that you get the codes in cronological order?

Thank you,
Zvamp

**Comment by LeagueOfPoro** [comment]
The problem is that the program doesn't know the account uses 2FA until it tries to log in.

So, the possible solution would be to label the 2FA in the config file, and them somehow orchestrate the login.

I am afraid that would way too much complexity.

**Comment by LeagueOfPoro** [comment]
Try this: https://github.com/LeagueOfPoro/CapsuleFarmerEvolved/releases/tag/v0.5.1-alpha
