### ISSUE TITLE
Traceback console error.

### ISSUE THREAD

**Issue by 2loopVoyvoda** [LeagueOfPoro/CapsuleFarmerEvolved#2]
Did all the things I need to do, got this error:
Traceback (most recent call last):
  File "D:\Capsule farmer V2\CapsuleFarmerEvolved-master\main.py", line 11, in <module>
    if browser.login(config.username, config.password):
  File "D:\Capsule farmer V2\CapsuleFarmerEvolved-master\Browser.py", line 37, in login
    if resJson.get("type", "") and resJson["response"].get("parameters", "") and resJson["response"]["parameters"].get("uri", ""):
KeyError: 'response'
Tried to fill the data in the config file, 0 success.

**Comment by fdarveau** [comment]
Do you have e-mail 2FA enabled?

I encountered the same problem when setting this up and it worked for me after removing the e-mail 2FA from my account at https://account.riotgames.com.

@LeagueOfPoro Is supporting 2FA in your plans?

**Comment by LeagueOfPoro** [comment]
2FA will most likely never be supported. However, if someone wants to give it a go and implement it, I will be more than happy to accept the PR.
