### ISSUE TITLE
[Suggestion]: Other ways of using Capsule Farmer Evolved

### ISSUE THREAD

**Issue by Ryoschin** [LeagueOfPoro/CapsuleFarmerEvolved#200]
### What is your idea?

I want to be able to use Capsule Farmer Evolved  while my pc is off. So adding android support, making some web page or telling me what do download or do in order for this to work would be great.

### What should happen?

My computer should be turned off and Capsule Farmer Evolved should still be farming capsules for me.

### My request is not a question

- [X] I acknowledge that this issue is not a question or a bug request.

**Comment by Trngd** [comment]
all of those things exist in the wiki...?

**Comment by Cawa425** [comment]
How do u even imagine how app is working when pc is off
Dude, are u even srs?

**Comment by WicCaesar** [comment]
I also wanted that, so I went on and read the description and found the exact instructions to install it on my Android.
