### ISSUE TITLE
Add verifyable pgp signature to binary releases/ Add checksums for downloads 

### ISSUE THREAD

**Issue by hackbard-sealion** [LeagueOfPoro/CapsuleFarmerEvolved#22]
Hi Poro,

as the project grows, at some point someone may try to distribute a malware version of the software. Two things could be done to somewhat reduce the risk of people getting tricked into downloading something different from your release:

1) After compiling the binary calculate the checksum (md5, sha1, sha256) of it and publish it with the releases and in release notes, so that people can verify they downloaded the same file you produced.

2) Sign the binaries with your pgp keys, so users can verify that you produced the build and not someone else that maybe got access to your github account [1]

Both verification steps should be added in the Readme to the install guide.

Of course this is for somewhat advanced users and results in more work for you, but maybe could save some people in the future.

[1] https://gist.github.com/cyphar/21a1b213901a0a0ec19764ac03646ebe

**Comment by LeagueOfPoro** [comment]
Great idea. However, I think it would prevent corrupted downloads at most. I see a couple of possible issues with the checksums:
- The checksums would need to be published in each release note. That means next to the correct download. If a user is already on that page, they will download the legit version anyway.
- Users who would verify the checksums would most likely run it directly in Python
The best solution would be to sign the app with a cert from CA. But they are quite expensive. If the channel starts doing better I will consider it.
