### ISSUE TITLE
[Suggestion]: Add 'expected results' for the Installation guide

### ISSUE THREAD

**Issue by Skubers** [LeagueOfPoro/CapsuleFarmerEvolved#23]
Hey

Could you please add what is 'expected' behavior for the steps in the Installation guide? For example, I'm running the .exe file, and it shows 'LOGIN' in green and closes after like 3 seconds later, and I don't know if I did something wrong, or is it working, or what is expected here.

**Comment by LeagueOfPoro** [comment]
I am making a video about the farmer
