### ISSUE TITLE
 this error window appearing about every half hour

### ISSUE THREAD

**Issue by S07453881** [LeagueOfPoro/CapsuleFarmerEvolved#24]
Hello, what is the problem with this error window appearing about every half hour or so after opening the software, and how to solve it?
![the error](https://user-images.githubusercontent.com/99027027/216215177-a182cb8e-ced5-42f7-b062-bb1434c2666c.png)

**Comment by LeagueOfPoro** [comment]
As long as the heartbeat time is within the last few minutes, it works. I will try to hide the message.
