### ISSUE TITLE
Can I run it on a external server

### ISSUE THREAD

**Issue by redcodemohammed** [LeagueOfPoro/CapsuleFarmerEvolved#26]
So I was wondering if running this tool on a server an not on my computer will get me banned.
I guess it would be more efficient since I will not have to keep my computer running

**Comment by kalinzange** [comment]
If you want to avoid getting banned, I'd recommend run the Capsule Farmer on a Raspberry Pi or Laptop that you no longer use.
This to avoid the IP Addresses and network data being different at such short time.

**Comment by redcodemohammed** [comment]
Yeah, I guess this makes sense, I would do this instead.
