### ISSUE TITLE
character " in password

### ISSUE THREAD

**Issue by Airveen** [LeagueOfPoro/CapsuleFarmerEvolved#27]
All my accounts work fine except one with a " in the password. I can't even start the exe if its added to the config.yaml. Any workaround besides changing the password?

**Comment by basseijger** [comment]
Put \" wherever the " needs to be

Example:
"password": "test\"password"

**Comment by basseijger** [comment]
Put a ```\"``` where the quote needs to be

Example:
Original password: test"test
In code:
```password: test\"test```

**Comment by Airveen** [comment]
worked out. ty sir!
