### ISSUE TITLE
Program crashing when \ in password

### ISSUE THREAD

**Issue by IngvarSchoenmaker** [LeagueOfPoro/CapsuleFarmerEvolved#29]
I tried running a program with the right values, but it still crashed. After some digging, I found the problem.
In my password is a character backslash (\\) this escapes the program, so it will crash.
I already resolved it for my self by escaping the escape (\\\\).

Error:
`yaml.scanner.ScannerError: while scanning a double-quoted scalar
  in "./config.yaml", line 4, column 15
found unknown escape character 'm'
  in "./config.yaml", line 4, column 19`

**Comment by LeagueOfPoro** [comment]
Yeah, backslash is usually an escape character - that way you can use " without interfering with the enclosing "
 Anyway, I will add note to FAQ. Glad you figured it out.
