### ISSUE TITLE
Mac support

### ISSUE THREAD

**Issue by pljjy** [LeagueOfPoro/CapsuleFarmerEvolved#30]
I know it's python and you cant just run ```python main.py```  with the source code. Most people might not know that so it would be pretty wholesome if you also made a mac version.

**Comment by Yunyun-Wang** [comment]
Agreed. I tried to run it on Mac directly and I can't login, stuck at Browser.py line 56. It would be great if it can also run on Mac.

**Comment by LeagueOfPoro** [comment]
@Yunyun-Wang most likely wrong password or username.

@pljjy I will try on Monday. I don't have access to a mac right now.

**Comment by auroraisluna** [comment]
Please check the Discord FAQ! If the issue persists, please reopen the issue using the new format :D
