### ISSUE TITLE
.Exe keeps Crashing

### ISSUE THREAD

**Issue by pijusz** [LeagueOfPoro/CapsuleFarmerEvolved#37]
I'm currently on 2 accounts.
One account manages to login, other keeps failing.

After I left single account, it shows "Login" status, but crashes after around a minute.

Any ideas?

**Comment by pijusz** [comment]
Found logs file, seems after I deleted Session and Logs folders it started to work again
[capsulefarmer-2023-02-03.log](https://github.com/LeagueOfPoro/CapsuleFarmerEvolved/files/10582069/capsulefarmer-2023-02-03.log)

**Comment by auroraisluna** [comment]
Try restarting the app if the issue re-appears (its typically a Riot API outage). If its the same error as the one in your logs the next time, please re-create this issue (as there is a new format!)
