### ISSUE TITLE
Login FAILED everytime i try to connect

### ISSUE THREAD

**Issue by emoji987** [LeagueOfPoro/CapsuleFarmerEvolved#4]
So the bot was working perfectly without any problem but i wanted to transfer it to my home VSP, and when i try to run it, i just get the Login FAILED error even tho my logs are written properly.

I tried restarting the script on my AWS VPS but it now says the same thing Login FAILED any idea?

**Comment by LeagueOfPoro** [comment]
It's possible Riot changed something.
I will continue/finish the development once the regular season starts. I can't really test or capture traffic when there are no matches live.

**Comment by LeagueOfPoro** [comment]
They indeed changed the login flow a bit. Try the new [multiaccount branch](https://github.com/LeagueOfPoro/CapsuleFarmerEvolved/tree/multiaccount). But it is very WIP right now

**Comment by LeagueOfPoro** [comment]
Update the config. The example is in readme.
