### ISSUE TITLE
[Feature] Refactor file structure

### ISSUE THREAD

**Issue by auroraisluna** [LeagueOfPoro/CapsuleFarmerEvolved#43]
The project currently has a lot of files that are generally unorganized and messy. They make sense due to proper naming by Poro but we should organize things a little. 

Proposing this file structure: 
```fixx
.github/
src/
   # Contains the Python files (Config.py, FarmThread.py, etc) and the pip files (if possible), poro icon, any sound files, etc
config/ 
   # Contains config.json / config.yaml and the 'bestStreams.txt' 
setup/ 
   # Various pre-made setup scripts (for docker, deployment in other hosting services or OSes, as well as 'self build' tools) 
LICENSE
README.md
CONDUCT.md
```

This isn't the best structure, frankly the current is just fine, but I believe if we can organize the project better and with subfolders, developing and maintaining it will become a piece of cake. 

This shouldn't affect the end user as they download the build version anyways, but rather developers that wish to jump in the project, so it's definitely beneficial!

**Comment by LeagueOfPoro** [comment]
I wanted to do the src folder for a long time and then never got around to doing it. The problem is moving the config to a separate folder would be a breaking change and it would require either specifying --config option or changing the default location.

**Comment by auroraisluna** [comment]
We don't have to require the config file on a different location, the folder is purely to contain the templates. Users will still need to create (or have it prebundled in releases) the config files on the same folders

**Comment by auroraisluna** [comment]
> o

To add to this, if it was a Node/NPM project you would be able to just create a command to automatically build it :P I don't know if PIP can do that, but we can just create an bash script for development to automatically build, copy the config template and bundle everything.

**Comment by auroraisluna** [comment]
Closing this issue as completed since PR #72 has been opened. 

For contributors: Please rebase your PRs to match the new paths, before submitting them.
