### ISSUE TITLE
[Suggestion]: Discord integration

### ISSUE THREAD

**Issue by KitsumyFox** [LeagueOfPoro/CapsuleFarmerEvolved#45]
### What is your idea?

Similar to the twitter bot poro has set up but locally. You could add another command on the config to forward the drops messages to one discord channel of your group. (A friends group or a larger community)

### What should happen?

Using webhooks from discord, something like:

You got one drop from "X League" on time "X"

Optionaly you could add your own discord tag as another variable, so the message above tags you when there is a drop for the notification sound.

### My request is not a question

- [X] I acknowledge that this issue is not a question or a bug request.

**Comment by KitsumyFox** [comment]
In addition to the above, another good use it will be to send a notification in case the bot completely stops, either LOGIN fails or crash.

**Comment by auroraisluna** [comment]
Added in v1.2
