### ISSUE TITLE
[Suggestion]: Add a uptime timer

### ISSUE THREAD

**Issue by basseijger** [LeagueOfPoro/CapsuleFarmerEvolved#47]
### What is your idea?

A timer which shows the time that the program has been running. Would be a fun QoL thing in my opinion.  

### What should happen?

Add a timer which shows time running

### My request is not a question

- [X] I acknowledge that this issue is not a question or a bug request.

**Comment by LeagueOfPoro** [comment]
One way is to check the logs. I will most likely not implement live timer but maybe `The program started at: XXXX`
![image](https://user-images.githubusercontent.com/95635582/216762147-facf7c5d-00cc-44b3-b0ca-145dbe55eb23.png)
