### ISSUE TITLE
[Bug]: Program crashes

### ISSUE THREAD

**Issue by Kapustaa** [LeagueOfPoro/CapsuleFarmerEvolved#49]
### What happened?

I've got "/" in my password and I guess it's causing the bug

### What should happen?

fix

### Capsule Farmer Version

v1.1

### Operating System

Windows 11

### My issue is not a question

- [X] I acknowledge that this issue is not a question or feature request.

**Comment by btvoidx** [comment]
Try surrounding your password with `"`, so `pa//w0rd` becomes `"pa//w0rd"`.

**Comment by auroraisluna** [comment]
This is a standard YAML issue. Add the password inside a string `"password"` and or try `"pass\\word"` (in case you have only one `\`)

Alternatively, change your password to not contain a backslash 😄
