### ISSUE TITLE
Github Action

### ISSUE THREAD

**Issue by Axel3026** [LeagueOfPoro/CapsuleFarmerEvolved#5]
How could you use github action to run only every day for a period of time?

**Comment by LeagueOfPoro** [comment]
You can use the "schedule" trigger in a GitHub Actions workflow to run the workflow on a specific schedule. For example, to run the workflow every day for a period of time, you can use the following syntax in the workflow file:

```
on:
  schedule:
  - cron: '0 0 * * *'  # run every day at 00:00
  - if: startsWith(github.event_name, 'schedule')
    && github.event.after == '2022-12-01T00:00:00Z'
    && github.event.before == '2022-12-31T23:59:59Z'
```
This will schedule the workflow to run every day at 00:00 and the cron schedule is only active between '2022-12-01T00:00:00Z' and '2022-12-31T23:59:59Z'

You can also use the runs-on and needs property in your workflow YAML file to specify the type of virtual machine and any required inputs for the job.

**Comment by Axel3026** [comment]
Sorry to bother you but do I need to edit something? Or do I copy and paste it?
Edit: github.event_name¿?

![image](https://user-images.githubusercontent.com/87623383/212285204-983d299e-a93a-40e9-a374-8c1be7e1cfe2.png)
![image](https://user-images.githubusercontent.com/87623383/212285282-07f9f8ad-9a09-47df-beb1-ae402f0c732c.png)
