### ISSUE TITLE
[Suggestion]: Display what stream the last drop came from

### ISSUE THREAD

**Issue by JonasTD** [LeagueOfPoro/CapsuleFarmerEvolved#57]
## This is a very minor thing but I personally, as well as a few others often open up the esports website to identify where the last drop came from.

# Would be a nice QOL addition to have it be displayed inside the farmer.
----
Love what you do, stay awesome!

### What should happen?

An additional column besides the **"Last drop"** column; either on _left or right_ to be added.
_Elsewhere is fine too._
### My request is not a question

- [X] I acknowledge that this issue is not a question or a bug request.

**Comment by LeagueOfPoro** [comment]
This code will retrieve League name by its ID.
```python
def getLeagueFromID(leagueId):
    allLeagues = getLeagues()
    for league in allLeagues:
        if leagueId in league["id"]:
            return league["name"]


def getLeagues():
    headers = {"Origin": "https://lolesports.com", "Referrer": "https://lolesports.com",
               "x-api-key": "0TvQnueqKa5mxJntVWt0w4LpLfEkrV1Ta8rQBb9Z"}
    res = requests.get(
        "https://esports-api.lolesports.com/persisted/gw/getLeagues?hl=en-GB", headers=headers)
    return res.json()["data"].get("leagues", [])
```

**Comment by auroraisluna** [comment]
Added in #96
