### ISSUE TITLE
[Typo]: README

### ISSUE THREAD

**Issue by Mazen-Ghaleb** [LeagueOfPoro/CapsuleFarmerEvolved#64]
### What happened?

In ReadME, there is the following typo "invrease" instead of increase
![image](https://user-images.githubusercontent.com/86268979/216847050-e2dee705-7bc0-42c8-80f0-6914e9861c3a.png)

### What should happen?

Switch it back to increase

### Capsule Farmer Version

v1.2

### Operating System

Windows 11

### My issue is not a question

- [X] I acknowledge that this issue is not a question or feature request.

**Comment by auroraisluna** [comment]
Thanks! https://github.com/LeagueOfPoro/CapsuleFarmerEvolved/commit/9b6fabac856e491ff7d4708cdbc0201214776fae
