### ISSUE TITLE
[Suggestion]: Sound Notification

### ISSUE THREAD

**Issue by Mazen-Ghaleb** [LeagueOfPoro/CapsuleFarmerEvolved#65]
### What is your idea?

I was inspired by suggestion of sound notification of drop (as suggested by [TimCZE](https://github.com/TimCZE)) to suggest a sound whenever status changes such as going from "Live" to "Login"/"Wait" or waiting for 2FA. This can be done by user input from the config.yaml file too by having another flag than drop notification.

Also, I would like to suggest to add in .gitignore logs and sessions folder as well as the config.yaml (it can be generated now from the webpage).

### What should happen?

- Sound Notification Example: 
![image](https://user-images.githubusercontent.com/86268979/216848981-d46db8bb-29b3-4f65-8030-764017dd8261.png)

### My request is not a question

- [X] I acknowledge that this issue is not a question or a bug request.

**Comment by auroraisluna** [comment]
I think partial features of this are being added by #69
