### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by EvilRammus** [LeagueOfPoro/CapsuleFarmerEvolved#73]
### What happened?

Program ran for a couple minutes seemed fine. Just shuts down randomly. Sometimes after a long period but no idea why

### What should happen?

Program keeps running until I shut it down...?

### Capsule Farmer Version

latest

### Operating System

Windows 10

### My issue is not a question

- [X] I acknowledge that this issue is not a question or feature request.

**Comment by auroraisluna** [comment]
Please check the Discord. You have most likely an error in your configuration. 

Have you went through the [Quickstart Guide](https://github.com/LeagueOfPoro/CapsuleFarmerEvolved/wiki/Quickstart-Guide-(Windows))?
Check the FAQ as well on the wiki.
