### ISSUE TITLE
[Bug]: Getting 2factor on my mail 

### ISSUE THREAD

**Issue by VirginitySnatcher** [LeagueOfPoro/CapsuleFarmerEvolved#77]
### What happened?

I am getting a 2factor code even tho I am logged in

### What should happen?

I shouldn't receive 2factor code if I am logged in already

### Capsule Farmer Version

v1.2

### Operating System

Windows 11

### Operating System Version

Version 22H2

### My issue is not a question

- [x] I acknowledge that this issue is not a question or feature request.

**Comment by DjordyKoert** [comment]
The farmer tries to re-login every once in a while to make sure the authentication tokens are set correctly (and not expired), this is the reason you are getting 2fa code in your email. 

Not a bug.

**Comment by VirginitySnatcher** [comment]
Ah okay ty
