### ISSUE TITLE
[Bug]: Raspberry Docker installation failed? No Docker console output

### ISSUE THREAD

**Issue by sirzento** [LeagueOfPoro/CapsuleFarmerEvolved#82]
### What happened?

I tryed to run the docker command and wanted to see the console output

![Console output](https://i.imgur.com/fn7ZkTp.png)

### What should happen?

It should show me the output of docker. Now I don't know if the farmer is running or not

### Capsule Farmer Version

Latest I guess because the docker command was used (1.2)

### Operating System

Other (Non Windows are not natively supported)

### Operating System Version

Debian GNU/Linux 11 (bullseye) - Linux/arm64/v8 running on raspberry pi 3

### Notes

Before I did use the local installed version that I needed to self compile. That did take ages but it was running fine.

### My issue is not a question

- [x] I acknowledge that this issue is not a question or feature request.

**Comment by Penguax** [comment]
I've encountered this but with docker-compose, it was solved doing 
`tty: true` in my compose file. I suspect doing `--tty=true` in the docker run command may do the same.

**Comment by DjordyKoert** [comment]
https://github.com/LeagueOfPoro/CapsuleFarmerEvolved/pull/36

Fixes this

**Comment by LeagueOfPoro** [comment]
Fixed in #56
